#!/bin/bash
DATADIR=/var/lib/postgresql/9.5/main

# test if DATADIR is existent
if [ ! -d $DATADIR ]; then
    echo "Creating Postgres data at $DATADIR"
    mkdir -p $DATADIR
fi

chown -R postgres $DATADIR

# test if DATADIR has content
if [ ! "$(ls -A $DATADIR)" ]; then
    echo "Initializing Postgres Database at $DATADIR"
    su postgres sh -c "/usr/lib/postgresql/9.5/bin/initdb --locale en_US.UTF-8 -E UTF8 -D $DATADIR"
fi

su postgres -c "/usr/lib/postgresql/9.5/bin/postgres -D $DATADIR -c config_file=/etc/postgresql/9.5/main/postgresql.conf -c listen_addresses=*"
