#!/bin/bash
printf 'Running tsung .... \n'
output=$(exec tsung -f onadata-small.xml start)

cleanedpath=$(exec echo $output | cut -c 35- | sed 's/.\r//')

printf 'Cleaned path:%s\n' $cleanedpath
 
if [ -d "$cleanedpath" ]; then
	# Generate the report if log path created
	printf 'Generating the report .... \n'
	( cd "$cleanedpath" && /usr/lib/tsung/bin/tsung_stats.pl )

	export AWS_ACCESS_KEY_ID="AKIAIE2IR7632AYAFBTA"
	export AWS_SECRET_ACCESS_KEY="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"
	export S3_BUCKET="whodcptest"
	export FOLDER="tsung-reports"
	export REGION="us-west-1"

	report="${cleanedpath##*/}"
	# Bash script to upload files to static s3 hosting
	printf 'Uploading the report to s3.... \n'
	exec aws --region $REGION s3 cp $cleanedpath s3://$S3_BUCKET/$FOLDER/$report --recursive 
fi
