name: Build Python Deps Image

on:
  release:
      types:
          - "released"
  push:
    branches:
      - "main"
      - "*-rc"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Prepare
        run: |
          echo "VERSION=3.10.14" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        id: login-docker-registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./python/3.10-deps/Dockerfile
          platforms: ${{ matrix.platform }}
          cache-from: type=registry,ref=${{ steps.login-docker-registry.outputs.registry }}/onaio/python-deps:${{ env.VERSION }}
          cache-to: type=inline
          push: true
          labels: |
            "${{ matrix.platform }}"
          provenance: false
          outputs: type=image,name=${{ steps.login-login-registry.outputs.registry }}/onaio/python-deps:${{ env.VERSION || github.ref_name }},push-by-digest=false,name-canonical=true,push=true

      - name: (Ubuntu) Image digest
        run: echo ${{ steps.docker-build-ubuntu.outputs.digest }}
